name: Recovery Build SM-A135F

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: device/samsung/a13

      - name: Install Repo
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync Source
        run: |
          mkdir ~/twrp && cd ~/twrp
          git config --global user.email "zorin@example.com"
          git config --global user.name "Zorin"
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Move Tree
        run: |
          mv $GITHUB_WORKSPACE/device/samsung/a13 ~/twrp/device/samsung/a13

      - name: Build
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          . build/envsetup.sh
          lunch twrp_a13-eng
          mka recoveryimage -j$(nproc)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-A135F-IMG
          path: /home/runner/twrp/out/target/product/a13/recovery.img